services:
  blinko-website:
    restart: unless-stopped
    image: blinkospace/blinko:1.2.2
    container_name: blinko-website
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_BASE_URL: ${DOMAIN}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXT_AUTH}
      DATABASE_URL: postgresql://blinko:${PG_PASS}@postgres:5432/blinko
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./data:/app/.blinko
    ports:
      - "1111:1111"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://blinko-website:1111/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    env_file:
      - .env

  postgres:
    restart: unless-stopped
    image: postgres:14
    container_name: blinko-postgres
    environment:
      POSTGRES_DB: blinko
      POSTGRES_USER: blinko
      POSTGRES_PASSWORD: ${PG_PASS}
      TZ: Europe/Amsterdam
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - blinko
        - -d
        - blinko
      interval: 5s
      timeout: 10s
      retries: 5
    env_file:
      - .env
